### Without Gateway

http://localhost:9002/value

### With Gateway

http://localhost:9000/aggregator/value

### With Token & Gateway

http://localhost:9000/aggregator/value
Authorization: top-secret

###

http://localhost:9002/api/payments

###

http://localhost:9000/aggregator/api/payments

###

POST http://localhost:9000/producer/api/payments
Content-Type: application/json

{
  "senderId": "3",
  "amount": "2000",
  "comment": "Transaction"
}

###